apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: uskh
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-dkdt-tenant/byoc-app-mojp/uskh@sha256:ec6b58bab93d986e1cbcd27f3b47accdb9e34f25b23dd57601f066fb6d6a95cd
        name: my-java-quarkus
        resources: {}
status: {}
