apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: uskh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uskh
    app.kubernetes.io/part-of: byoc-app-mojp
  name: uskh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: uskh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: uskh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-dkdt-tenant/byoc-app-mojp/uskh@sha256:ec6b58bab93d986e1cbcd27f3b47accdb9e34f25b23dd57601f066fb6d6a95cd
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
